Parameters:
  vpcID:
    Type: String
  DBuserName:
    Type: String
  DBpassword:
    Type: String    
  subnetID1:
    Type: String
  subnetID2:
    Type: String
  subnetID3:
    Type: String    
  subnetID:
    Type: String
  HostedZoneName:
    Type: String    
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  EncryptedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'csye6225-fall2018-chengl.me.csye6225.com'
      AccessControl: PublicRead
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: 'id'
        AttributeType:  'S'
      KeySchema:
      - AttributeName: 'id'
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable datebase.service port 3306
      VpcId: !Ref vpcID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 0.0.0.0/0
  myDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: csye6225 webApp
      SubnetIds:
      - !Ref subnetID1
      - !Ref subnetID2
      - !Ref subnetID3
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: csye6225
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.medium
      DBInstanceIdentifier: 'csye6225-spring2018'
      Engine: MySQL
      MasterUsername: !Ref DBuserName
      MasterUserPassword: !Ref DBpassword
      DBSubnetGroupName: !Ref myDBSubnetGroup
      VPCSecurityGroups:
      - !Ref DBSecurityGroup
