
Resources:
  testStackCsye6225Vpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 192.168.0.0/16
  csye6225Subnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 192.168.0.0/24
      VpcId:
        Ref: testStackCsye6225Vpc
  csye6225Subnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 192.168.1.0/24
      VpcId:
        Ref: testStackCsye6225Vpc
  csye6225Subnet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 192.168.2.0/24
      VpcId:
        Ref: testStackCsye6225Vpc
  testStackCsye6225InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref testStackCsye6225Vpc
      InternetGatewayId: !Ref testStackCsye6225InternetGateway
  testStackCsye6225PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref testStackCsye6225Vpc
  SubnetRouteAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref testStackCsye6225PublicRouteTable
      SubnetId: !Ref csye6225Subnet1
  SubnetRouteAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref testStackCsye6225PublicRouteTable
      SubnetId: !Ref csye6225Subnet2
  SubnetRouteAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref testStackCsye6225PublicRouteTable
      SubnetId: !Ref csye6225Subnet3
  AddGatewayRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref testStackCsye6225PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref testStackCsye6225InternetGateway


